<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CustomerServiceApplication/CustomerService/CreateCustomerDBAdapter"
                  name="CreateCustomerDBAdapter-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import location="CreateCustomerDBAdapter.wsdl"
               namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CustomerServiceApplication/CustomerService/CreateCustomerDBAdapter"/>
  <wsdl:binding name="CreateCustomerDBAdapter_ptt-binding" type="cre:CreateCustomerDBAdapter_ptt"
                xmlns:cre="http://xmlns.oracle.com/pcbpel/adapter/db/CustomerServiceApplication/CustomerService/CreateCustomerDBAdapter">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <wsdl:operation name="CreateCustomerDBAdapter">
      <soap:operation soapAction="CreateCustomerDBAdapter"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>