<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/CustomerServiceApplication/CustomerService/GetCustomerDBAdapter"
                  name="GetCustomerDBAdapter-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import location="GetCustomerDBAdapter.wsdl"
               namespace="http://xmlns.oracle.com/pcbpel/adapter/db/CustomerServiceApplication/CustomerService/GetCustomerDBAdapter"/>
  <wsdl:binding name="GetCustomerDBAdapter_ptt-binding" type="get:GetCustomerDBAdapter_ptt"
                xmlns:get="http://xmlns.oracle.com/pcbpel/adapter/db/CustomerServiceApplication/CustomerService/GetCustomerDBAdapter">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <wsdl:operation name="GetCustomerDBAdapter">
      <soap:operation soapAction="GetCustomerDBAdapter"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>