<?xml version="1.0" encoding="windows-1252" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://osb.training/customer"
            xmlns:tns="http://osb.training/customer" targetNamespace="http://osb.training/customer"
            elementFormDefault="qualified">
  <xsd:include schemaLocation="../Common/CustomerType.xsd"/>
  <xsd:element name="UpdateCustomerRequest">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="CustomerId">
          <xsd:simpleType>
            <xsd:restriction base="xsd:int">
              <xsd:minInclusive value="1"/>
            </xsd:restriction>
          </xsd:simpleType>
        </xsd:element>
        <xsd:element name="PrimaryCustomer" type="tns:CustomerType"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>
